"""
Email Notification Service for AI Video Factory

Sends email notifications when videos complete or errors occur.
Uses Gmail SMTP with App Password authentication.
"""
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional


class EmailService:
    """Email notification service using SMTP."""
    
    def __init__(self):
        self.smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        self.smtp_user = os.getenv("SMTP_USER")
        self.smtp_pass = os.getenv("SMTP_PASS")
        self.notification_email = os.getenv("NOTIFICATION_EMAIL")
        
    def is_configured(self) -> bool:
        """Check if email service is properly configured."""
        return all([
            self.smtp_user,
            self.smtp_pass,
            self.notification_email
        ])
    
    def send_email(
        self, 
        subject: str, 
        body_html: str, 
        to_email: Optional[str] = None
    ) -> bool:
        """
        Send an email notification.
        
        Args:
            subject: Email subject line
            body_html: HTML content for email body
            to_email: Optional recipient (defaults to NOTIFICATION_EMAIL)
            
        Returns:
            True if sent successfully, False otherwise
        """
        if not self.is_configured():
            print("[Email] Not configured - skipping notification")
            return False
            
        recipient = to_email or self.notification_email
        
        try:
            msg = MIMEMultipart("alternative")
            msg["From"] = self.smtp_user
            msg["To"] = recipient
            msg["Subject"] = subject
            msg.attach(MIMEText(body_html, "html"))
            
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_pass)
                server.send_message(msg)
                
            print(f"[Email] Sent to {recipient}: {subject}")
            return True
            
        except Exception as e:
            print(f"[Email] Failed to send: {e}")
            return False
    
    def send_video_complete(
        self, 
        project_name: str, 
        video_url: str,
        channel_name: Optional[str] = None
    ) -> bool:
        """Send notification when video generation completes."""
        subject = f"✅ Video Ready: {project_name}"
        body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
            <h2 style="color: #22c55e;">🎬 Your Video is Ready!</h2>
            <p><strong>Project:</strong> {project_name}</p>
            {f'<p><strong>Channel:</strong> {channel_name}</p>' if channel_name else ''}
            <p><strong>Video URL:</strong></p>
            <p><a href="{video_url}" style="color: #3b82f6;">{video_url}</a></p>
            <hr style="border: 1px solid #e5e7eb; margin: 20px 0;">
            <p style="color: #6b7280; font-size: 12px;">
                Generated by AI Video Factory
            </p>
        </body>
        </html>
        """
        return self.send_email(subject, body)
    
    def send_video_error(
        self, 
        project_name: str, 
        error_message: str,
        step: Optional[str] = None
    ) -> bool:
        """Send notification when video generation fails."""
        subject = f"❌ Video Failed: {project_name}"
        body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
            <h2 style="color: #ef4444;">⚠️ Video Generation Failed</h2>
            <p><strong>Project:</strong> {project_name}</p>
            {f'<p><strong>Failed at:</strong> {step}</p>' if step else ''}
            <p><strong>Error:</strong></p>
            <pre style="background: #fef2f2; padding: 15px; border-radius: 5px; color: #dc2626;">
{error_message}
            </pre>
            <hr style="border: 1px solid #e5e7eb; margin: 20px 0;">
            <p style="color: #6b7280; font-size: 12px;">
                AI Video Factory
            </p>
        </body>
        </html>
        """
        return self.send_email(subject, body)
    
    def send_queue_status(
        self,
        total_items: int,
        completed: int,
        errors: int
    ) -> bool:
        """Send daily queue summary."""
        subject = f"📊 Queue Summary: {completed}/{total_items} completed"
        body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
            <h2 style="color: #3b82f6;">📊 Daily Queue Summary</h2>
            <table style="border-collapse: collapse; width: 100%; max-width: 400px;">
                <tr>
                    <td style="padding: 10px; border: 1px solid #e5e7eb;">Total Items</td>
                    <td style="padding: 10px; border: 1px solid #e5e7eb;"><strong>{total_items}</strong></td>
                </tr>
                <tr>
                    <td style="padding: 10px; border: 1px solid #e5e7eb;">Completed</td>
                    <td style="padding: 10px; border: 1px solid #e5e7eb; color: #22c55e;"><strong>{completed}</strong></td>
                </tr>
                <tr>
                    <td style="padding: 10px; border: 1px solid #e5e7eb;">Errors</td>
                    <td style="padding: 10px; border: 1px solid #e5e7eb; color: #ef4444;"><strong>{errors}</strong></td>
                </tr>
            </table>
            <hr style="border: 1px solid #e5e7eb; margin: 20px 0;">
            <p style="color: #6b7280; font-size: 12px;">
                AI Video Factory
            </p>
        </body>
        </html>
        """
        return self.send_email(subject, body)


# Singleton instance
email_service = EmailService()
